### ISSUE TITLE
你好，我想请教您一下，lstm训练 这个文件中的ec_lstm.ipynb是怎么把训练好的模型保存起来的？

### ISSUE THREAD

**Issue by liuhongxiao** [xiaohuiduan/network-traffic-predict#1]
您好，我想请教您一下，lstm训练 这个文件中的ec_lstm.ipynb是怎么把训练好的模型保存起来的？

**Comment by xiaohuiduan** [comment]
在我的代码中，我没有将模型保存起来。如果你想将训练好的模型保存起来，你可以参考https://keras.io/api/models/model_saving_apis/，在官方文档中详细介绍了如何保存keras的模型

**Comment by xiaohuiduan** [comment]
@liuhongxiao 问题已经解决了吗？

**Comment by liuhongxiao** [comment]
已经解决了，在最后加一句“lstm.save('my_model.h5')”就可以了，非常感谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaohuiduan/network-traffic-predict"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月20日(星期三) 上午9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaohuiduan/network-traffic-predict] 你好，我想请教您一下，lstm训练 这个文件中的ec_lstm.ipynb是怎么把训练好的模型保存起来的？ (Issue #1)





 
@liuhongxiao 问题已经解决了吗？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaohuiduan** [comment]
好的，那我close这个issue了
